Sprint Task: Color/Font Setup
calblueprint/vouchers4veggies pull request #3
Opened 2022-10-07 01:19 UTC by EthanAuyeung

Setup the color and fonts on Figma style guide using styled components/TypeScript.

No physical things to test, just setup

Shouldn't have any bugs.

2022-10-08 20:14 UTC, oahnh requested changes
Nice job with setting up! Check comments for changes

2022-10-08 20:14 UTC, oahnh commented on assets/FontDownloads/License.txt
> +�X------------------------------------------------------�[
Download the font from google fonts: https://fonts.google.com/specimen/Manrope > download font family

2022-10-08 20:14 UTC, oahnh commented on assets/Colors.tsx
> +	brightMagenta: '#BD25B4',
good! minor formatting issue, just make sure everything's on the same indentation

2022-10-08 20:14 UTC, oahnh commented on assets/FontDownloads/License.txt
> +��     FREE FONT : http://www.OnlineWebFonts.Com      ��
Download the font straight from Google: https://fonts.google.com/specimen/Manrope > Download Family

2022-10-09 21:16 UTC, EthanAuyeung commented
# ✨ New in this PR ✨

## One liner: what did you do? 🚨 
Fixed comments for fonts and styling, indenting and imported fonts from google.


## Coverage 🙆‍♀️


## How can the reviewer test your code? 👩‍💻
N/A just setup

## Any bugs you encountered or still having trouble with? 🐛
I'm not sure if the way on the formatting guide is completely correct because when I searched online they wanted me to use some global formatting stuff but we can always test later.

## Resources 📔
_link online resources and related PRs_ 

🥦 CC: @oahnh

2022-10-09 22:23 UTC, EthanAuyeung commented
✨ New in this PR ✨
One liner: what did you do? 🚨
Fixed comments for fonts and styling, indenting and imported fonts from google further.

Coverage 🙆‍♀️
How can the reviewer test your code? 👩‍💻
N/A just setup

Any bugs you encountered or still having trouble with? 🐛
N/A

Resources 📔
link online resources and related PRs

🥦 CC: @oahnh

2022-10-11 07:20 UTC, oahnh approved these changes

2022-10-11 07:20 UTC, merged