Completed sign-up screens
calblueprint/vouchers4veggies pull request #30
Opened 2022-12-02 05:05 UTC by allisonhongberkeley

# ✨ New in this PR ✨

## One liner: what did you do? 🚨 
Finished the sign-up page and create password screens (only front end)

## Coverage 🙆‍♀️
_use this section to break up your task into submodules and track progress_ 
 - [ ] Task 1 
 - [ ] Task 2 

## How can the reviewer test your code? 👩‍💻
_example: run `npm start` and click through Navigation bar_ 

## Any bugs you encountered or still having trouble with? 🐛
_describe how you solved them such that someone can follow your explanation_ 

## Resources 📔
_link online resources and related PRs_ 

🥦 CC: @oahnh

2022-12-02 08:24 UTC, oahnh requested changes

2022-12-02 08:24 UTC, oahnh commented on src/components/InputField/PasswordInput.tsx
> +      <Pressable onPress={handlePasswordVisibility}>
Alignment for the eye button appears outside the container. Also, the icon should be an outline. 

![IMG_0AD58169CA9A-1](https://user-images.githubusercontent.com/63211322/205230534-65a2b494-43a7-4c13-b99a-ea08be6b8163.jpeg)

2022-12-02 08:24 UTC, oahnh commented on src/screens/auth/SignupScreen.tsx
> +            <Body_1_Text style={Styles.underline}>Login</Body_1_Text>
Make login button clickable here, so that we can route to the Login screen.

2022-12-02 09:41 UTC, oahnh commented
Good job on this PR! Just some styling + functionality tweaks, next steps will be adding the auth functionality to this screen.

2022-12-03 23:44 UTC, wangannie requested changes
Great work on this Allison! I left a couple comments on refactoring a few places + code cleanup. Please also make sure to address the eslint errors (run `npx eslint .` to get the full printout). 

Please don't hesitate to reach out if you wanna walk through any of my comments / working through linter errors!

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +    //write data to firebase
Nit: add 'TODO' to for consistency

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +          style={{ backgroundColor: 'black', width: 50, height: 59.29 }}
Don't use inline styles! You should do this in a style sheet. See how this is done in LoginScreen as an example.

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +  const [confirm, confirmPassword] = useState('');
This should be `confirmPassword` and `setConfirmPassword` to follow useState naming convention

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +import { Text, View } from 'react-native';
This file should be named `CreatePasswordScreen` to follow the convention of the other screens (e.g. `SignupScreen`)

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/SignupScreen.tsx
> +  // const { authState, dispatch } = useAuthContext();
Make sure to make a final pass through your changes to remove comments like this before making PRs

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/SignupScreen.tsx
> +          <ButtonMagenta onPress={() => navigation.navigate('Create Password')}>
In this case, since there are multiple actions we need to do upon submitting, it makes more sense to keep a `submitForm` function rather than navigating directly.

You should put the `navigation.navigate...` in the `submitForm`.

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/SignupScreen.tsx
> +  const submitForm = () => {
Nit: `handleSubmit` is a better name for this, since it's an event handler.

See https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/SignupScreen.tsx
> +    //transfer data to createPassword screen
Make these into TODO comments so it's easy to tell that they are actionable

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/SignupScreen.tsx
> +            Already have an account?{' '}
Turn this into a template string to include the space

```
{`Already have an account `}
```

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +import { useAuthContext } from './AuthContext';
Make sure to remove unused imports

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +  togglePasswordVisibility,
Unused import

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/StartScreen.tsx
> +            <ButtonMagenta onPress={() => navigation.navigate('Sign Up')}>
(unrelated to this line) can you add this navigation to the Sign Up hyperlink in the LoginScreen too?

2022-12-03 23:44 UTC, wangannie commented on src/components/InputField/PasswordInput.tsx
> +export const PasswordInput = (props: any) => {
Since this should be styled similarly to the existing InputField just with the addition of the visibility button, it'd be cleaner to consolidate by using the InputField component and introduce a prop (maybe something like `showVisibilityToggle`) to toggle whether or not to include the icon button.

Basically, you'd put this new logic into `InputField` and conditionally render the icon button based on the new prop.

2022-12-03 23:44 UTC, wangannie commented on src/components/InputField/PasswordInput.tsx
> +            color="#232323"
This should use `Colors.darkGray`

Also `darkGray` should be `#525454`, not `#272929` -- you can go ahead and fix that.

2022-12-03 23:44 UTC, wangannie commented on src/components/InputField/PasswordInput.tsx
> +export const togglePasswordVisibility = () => {
Why did you make a helper for this? This is pretty much the same as just creating some `useState` variables for input field, so I'd recommend not extracting them into a helper for readability.

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/SignupScreen.tsx
> +          <ButtonMagenta onPress={() => navigation.navigate('Createpassword')}>
This should be Pascal Case (CreatePassword)

2022-12-03 23:44 UTC, wangannie commented on src/navigation/stacks/AuthStackNavigator.tsx
> +      <AuthStack.Screen name="Createpassword" component={CreatePassword} />
This should be Pascal Case (CreatePassword)

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +// import { useAuthContext } from './AuthContext';
Remove comments like this

2022-12-03 23:44 UTC, wangannie commented on src/screens/auth/CreatePassword.tsx
> +            style={{ lineHeight: 20 }}
Why did you need in-line styling for this line height?

2023-02-23 22:33 UTC, sauhardjain reviewed
Closing this PR for now as we are tentatively removing the sign-up flow from the app.

2023-02-23 22:34 UTC, closed without merging