Implement back button on login screen
calblueprint/vouchers4veggies pull request #47
Opened 2023-02-23 21:18 UTC by ronniebeggs

[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
- Created a back button component that reroutes the user to the starting page
- Styled the button using react native icons
- Replaced logo placeholder

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy!"
![back-button](https://user-images.githubusercontent.com/66931067/221030579-3891d96c-68e8-470e-aa89-c612c315f530.jpg)

## How to review
[//]: # "Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?"
- Run the app and log out if you're already signed in
- Navigate from the starting screen to the login screen
- Press the back button in the top left corner; it should take you back to the starting screen

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."
- Ensure that styling is consistent with the rest of the app
- Abstract the button as a component for use on other screens

### Online sources
[//]: # "Optional - copy links to any tutorials or documentation that was useful to you when working on this PR"
Using react-native-vector-icon library: https://aboutreact.com/react-native-vector-icons/

### Related PRs
[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"
[Annie's navigation structure PR](https://github.com/calblueprint/vouchers4veggies/pull/19)
[Noah's auth navigation PR](https://github.com/calblueprint/vouchers4veggies/pull/22)

[//]: # "This tags the project leader as a default. Feel free to change, or add on anyone who you should be in on the conversation."
🥦 CC: @sauhardjain

2023-02-23 21:45 UTC, sauhardjain requested changes
GREAT PR @ronniebeggs! Left a few comments — mostly nits about styling practices. Should be ready to merge once these are resolved.

2023-02-23 21:45 UTC, sauhardjain commented on assets/Components.tsx
> +  width: 20%;
Good practice to use `px` instead of percentages while styling buttons.

2023-02-23 21:45 UTC, sauhardjain commented on assets/Components.tsx
> +  font-weight: 500;
Remove the `font-weight` because it doesn't affect the icons.

2023-02-23 21:45 UTC, sauhardjain commented on src/screens/auth/LoginScreen.tsx
> +          </Text>
Replace the `<Text>` tag with the pre-styled `DarkGrayText`.

2023-02-23 21:45 UTC, sauhardjain commented on src/screens/auth/LoginScreen.tsx
> +            <Icon name="left" size={14} color="#525454" /> Back
Use the darkGray color from our global `Colors.ts` file. You can do this by setting the color as `${Colors.darkGray}`.

2023-02-23 21:45 UTC, sauhardjain commented on assets/Components.tsx
> +  color: #525454;
We shouldn't have any text styling as part of a styled button. Shift this into a styled Text container if required.

2023-02-24 00:06 UTC, sauhardjain approved these changes
LGTM

2023-02-24 00:06 UTC, merged

2023-03-03 05:34 UTC, wangannie commented on src/screens/auth/LoginScreen.tsx
> +}: AuthStackScreenProps<'Start'>) {
Pretty sure this should be 'Login' instead 

@ronniebeggs @sauhardjain