Add ZOD validation to input fields
calblueprint/vouchers4veggies pull request #49
Opened 2023-03-02 05:52 UTC by ronniebeggs

[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
- Added basic input validation to input fields on the login and manual voucher input screens
- Uses ZOD library to parse inputs and guarantee proper types/ minimum input lengths
- Validation functions triggered when the user unfocuses from an input field (currently just throws the error)
- Added a prop to the input field component that triggers a different keypad type depending on the input

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy!"

Image Order of Keyboard Types: Number --> Decimal --> Email
<img src="https://user-images.githubusercontent.com/66931067/222340748-859c9c77-3d45-4a47-88bd-36ac8eebaa77.PNG" width="200" height="400"> <img src="https://user-images.githubusercontent.com/66931067/222340754-9c6adff3-9360-4f37-a50b-1560c5179373.PNG" width="200" height="400"> <img src="https://user-images.githubusercontent.com/66931067/222340755-cf1d44b3-cb6f-45f1-bc1e-f36a336bd4cd.PNG" width="200" height="400">

https://user-images.githubusercontent.com/66931067/222340759-96766a4f-be0f-4015-9b58-c05542253274.mov

The video above triggers an error from the empty input, which isn't a valid email expression.

## How to review
[//]: # "Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?"
- Try various inputs in the login input fields, and watch as errors populate the console
- Login and navigate to the manual voucher input screen
- Similarly try various invalid inputs and observe errors
- Notice that inputs fields use different keyboard types

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."
- Catch and display errors for the user 
- Create a more comprehensive input validation procedure for currency inputs

### Online sources
[//]: # "Optional - copy links to any tutorials or documentation that was useful to you when working on this PR"
[ZOD Documentation](https://zod.dev/?id=numbers)

[//]: # "This tags the project leader as a default. Feel free to change, or add on anyone who you should be in on the conversation."
🥦 CC: @sauhardjain

2023-03-04 02:46 UTC, selene-huang commented
Excellent work Ronnie! Some issues I noticed while testing:

- Transaction ID has the option to put both decimal points and - signs on my keyboard, these should probably be disabled!
- Voucher amount had the - sign disabled but not the decimal point - I recall seeing a discussion about displaying things as a dollar amount, but forcing users to input as cents?
- Seems like you're validating transaction ID & voucher amount both as strings. Given the input types you've provided, this is actually the same as having no validation! I think it would make sense for them to be evaluated as integers instead.

I would give feedback on the login screen too, but I was actually completely unable to open the login screen on my phone for testing. Since I can't open it on main either, I don't think this has anything to do with your PR though.

2023-03-04 22:58 UTC, sauhardjain requested changes
Great work so far! Some other bugs to tackle in addition to the ones Selene pointed out:
- [x] Add a max limit of 10 dollars to the voucher value input box.
- [x] Find a way to add a Done button to the numeric keyboards because currently there's no way to close these keyboards.

![IMG_BD1EDF4669A9-1](https://user-images.githubusercontent.com/33095991/222932267-98204256-115e-4516-9329-756da11daf51.jpeg)

- [x] On the login screen, Zod simultaneously throws an error for both the email and password even if the user has only inputted one out of the two incorrectly.

![IMG_EDE1F83F60E3-1](https://user-images.githubusercontent.com/33095991/222932418-4afc9a58-81a8-442f-94ab-9c7dbeca3fc8.jpeg)

2023-03-11 20:11 UTC, wangannie requested changes
Looks really good! Mostly noted thoughts on code cleanup. They should be quick fixes : )

2023-03-11 20:11 UTC, wangannie commented on src/screens/scanning/ManualVoucherScreen.tsx
> +Logs.enableExpoCliLogging();
Remove?

2023-03-11 20:11 UTC, wangannie commented on src/screens/scanning/ManualVoucherScreen.tsx
> +  const SNonChange = (text: string) => {
Rename to `onChangeSerialNumber`

2023-03-11 20:11 UTC, wangannie commented on src/screens/scanning/ManualVoucherScreen.tsx
> +  const VAonChange = (text: string) => {
Rename to `onChangeVoucherAmount`

2023-03-11 20:11 UTC, wangannie commented on src/screens/scanning/ManualVoucherScreen.tsx
> +  const validateCurrencyFormat = (input: string) => {
I would move these validation functions to a separate util file like `validationUtils.ts` or `voucherUtils.ts` in the `src/utils` folder.

2023-03-11 20:11 UTC, wangannie commented on src/components/InputField/InputField.tsx
> +      keyboardType={inputMode}
`inputMode` is also a prop on `TextInput` right? you could probably use that directly

2023-03-11 20:11 UTC, wangannie commented on src/screens/auth/LoginScreen.tsx
> +    if (password !== '') {
We're removing these checks right?

2023-03-11 20:11 UTC, wangannie commented on src/screens/auth/LoginScreen.tsx
> +  const validateEmailInput = () => {
Similarly I would add these to a file like `validationUtils`

2023-03-11 21:01 UTC, wangannie approved these changes
LOOKS GREAT! A few more nits, but good to merge after!

2023-03-11 21:01 UTC, wangannie commented on src/components/InputField/InputField.tsx
> +      keyboardType={keyboard}
nit: for consistency, in most cases we'd wanna match the name of the props we're overriding so `keyboardType` instead of `keyboard`

2023-03-11 21:01 UTC, wangannie commented on src/utils/validationUtils.ts
> +  // confirms that any input has either 0 or 2 decimal digits
I like that you included a comment! Super helpful. I would also just move this to a docstring so it shows up nicely in VSCode

```
/**
 * .. your comment...
 */
```

2023-03-12 00:38 UTC, sauhardjain approved these changes

2023-03-12 00:39 UTC, merged