[transactions] Implement hifi Transactions screen and Transaction Details screen
calblueprint/vouchers4veggies pull request #54
Opened 2023-03-09 10:22 UTC by selene-huang

[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
- Updated Transactions screen to match hifi designs
- Added functionality to click on the entire transaction row instead of only the icon
- Added a Transaction Details screen
- Connected to Firebase so that both screens display actual data instead of dummy data
- Updated navigation functionality to allow for navigating between Transactions and Transaction Details

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy!"
![image](https://user-images.githubusercontent.com/57937407/223993868-7f2bf9ec-7403-4022-bf79-a9eb9f44a4b6.png)
![image](https://user-images.githubusercontent.com/57937407/223993926-ca265cc2-2a32-4499-a302-eeaf6fdd7670.png)

## How to review
[//]: # "Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?"
Run `npx expo start` and navigation to the Transactions screen. Verify that the transactions are scrollable and are displaying properly.

To check the Transaction Details screen, it's important that you click on the transaction labeled $10.12. Any other transaction will error due to recent schema changes.

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."
- Filtering will be added in future PRs
- Vendor UUID is currently hard-coded; this will later be linked to the auth context

### Online sources
[//]: # "Optional - copy links to any tutorials or documentation that was useful to you when working on this PR"
Ran into a bug with an "excessive number of pending callbacks". This was resolved by adding an additional dependency to the useEffect.

### Related PRs
[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"
Updated midfi code from #13 

[//]: # "This tags the project leader as a default. Feel free to change, or add on anyone who you should be in on the conversation."
🥦 CC: @sauhardjain

2023-03-11 23:31 UTC, kbrgl requested changes
Great PR! Left some nitpicks in the comments, but overall solid work :)

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/TransactionCard.tsx
> +          <H3Subheading>${(value / 100).toFixed(2)}</H3Subheading>
Could be good to factor out the `${(value / 100).toFixed(2)}` stuff into a separate function called `formatCentsForDisplay` or something, seems like it's used in multiple places. Add this function in a new file under the `src/utils/` folder

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/VoucherCard.tsx
> +        <Body1SemiboldText>${(value / 100).toFixed(2)}</Body1SemiboldText>
Use the `formatCentsForDisplay` function I mentioned in the other comment

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/styles.ts
>  export const Styles = StyleSheet.create({
Strictly speaking, `Styles` should instead be lowercase—`styles`. Capitalized first letter is convention for components (which all the styled component definitions above implicitly are).

But perhaps that's something to change in a different PR, since you didn't add this in this PR? Ask Annie :)

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/TransactionDetailsScreen.tsx
> +      ) : null}
Instead of showing nothing when the data hasn't been loaded yet, show a spinner?

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +export const Body1BoldText = styled.Text`
Use a more descriptive name, I know there's some notion of `Body1Text` in this codebase but that needs to be changed so may as well get a headstart

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  border-top-width: 1px;
You don't need two lines here, you can just do `border-top: `1px solid ${Colors.lightGray}`

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/styles.ts
> +  line-height: 19px;
Specify line height as a decimal ratio (e.g. 1.1, 1.7). In this case it'll be 1.35 since 19/14 = 1.35.

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/styles.ts
> +  line-height: 14px;
Specify line-height as a decimal ratio

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/styles.ts
> +  line-height: 14px;
Specify line-height as a decimal ratio

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  line-height: 57px;
Specify line-height as a decimal ratio

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  line-height: 22px;
Specify line-height as a decimal ratio

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  line-height: 19px;
Specify line-height as a decimal ratio

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  margin-left: 15%;
Get rid of %age here, replace with pixels

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  margin-top: 15%;
Get rid of %age here, replace with pixels

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/styles.ts
> +  margin-left: 15%;
Get rid of %age here, replace with pixels

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/styles.ts
> +  padding: 9px 9px;
Don't need to do `padding: 9px 9px`, can just do `padding: 9px` to specify all at once

2023-03-11 23:31 UTC, kbrgl commented on src/components/Transactions/styles.ts
>  `;
Replace with `border-bottom: 1px solid ${Colors.lightGray};`

2023-03-11 23:31 UTC, kbrgl commented on src/screens/Transactions/TransactionsScreen.tsx
> +          const vendor = await getVendorByEmail(user.email);
The vendor UUID should probably also be stored in the auth context, so that it only needs to be fetched once.

2023-03-11 23:55 UTC, selene-huang commented on src/components/Transactions/styles.ts
>  export const Styles = StyleSheet.create({
we'll be having a major refactoring PR next, so I will keep that in mind for then

2023-03-13 21:24 UTC, sauhardjain approved these changes
GREAT WORK @selene-huang! Everything looks great, some styling nits but we'll go over these when refactoring the flow's styling later.

2023-03-13 21:24 UTC, sauhardjain commented on src/components/Transactions/styles.ts
>  export const Styles = StyleSheet.create({
good catch @kbrgl

2023-03-13 21:24 UTC, sauhardjain commented on src/screens/Transactions/styles.ts
> +  margin-left: 10%;
Use px for margins

2023-03-13 21:32 UTC, kbrgl requested changes
Looks great! Just one last thing: the LoadingSpinner component should be used as `<LoadingSpinner />`, not as `LoadingSpinner()`. The latter technically works, but it is incorrect. You can see https://github.com/calblueprint/vouchers4veggies/blob/1ca79100b412d6fda0a4a66c68b073bf400d7533/src/navigation/AppNavigator.tsx#L13 for an example.

2023-03-13 21:35 UTC, kbrgl commented
> Looks great! Just one last thing: the LoadingSpinner component should be used as `<LoadingSpinner />`, not as `LoadingSpinner()`. The latter technically works, but it is incorrect. You can see
> 
> https://github.com/calblueprint/vouchers4veggies/blob/1ca79100b412d6fda0a4a66c68b073bf400d7533/src/navigation/AppNavigator.tsx#L13
> 
> for an example.

For details on why it is incorrect to *call* a function component, instead of rendering it (as `<LoadingSpinner />`), see here: https://kentcdodds.com/blog/dont-call-a-react-function-component. It can cause hard-to-debug errors!

2023-03-13 21:36 UTC, kbrgl approved these changes

2023-03-13 21:38 UTC, merged