Created a new branch that is updated to main and fixed all prettier/eslint errors with past PR
calblueprint/vouchers4veggies pull request #61
Opened 2023-03-20 20:03 UTC by EthanAuyeung

## What's new in this PR
### Description
[//]: # Created a new branch due to rebasing issues this branch is up to date with main and all the past errors have been fixed so should be ready for review and merge. 

## How to review
[//]: # Run npm start and interact with profile screen portion of the app.

[//]: # "This tags the project leader as a default. Feel free to change, or add on anyone who you should be in on the conversation."
🥦 CC: @sauhardjain @selene-huang

2023-03-22 05:56 UTC, selene-huang requested changes
Looks fine overall, but there's a couple bugs that should be addressed.

2023-03-22 05:56 UTC, selene-huang commented on src/screens/profile/styles.ts
> +  font-family: 'Manrope';
The profile screen crashes on my phone. I think the error is coming from here - this should probably be `manrope-regular`, in line with the font we actually have loaded.

2023-03-22 05:56 UTC, selene-huang commented on src/screens/profile/ProfileScreen.tsx
> +        {/* logo placeholder */}
you should probably remove this comment since the actual logo is there

2023-03-22 05:56 UTC, selene-huang commented on src/screens/profile/styles.ts
> +  flex-direction: top;
I don't think this is standard practice? While it may work on IOS, it crashes the app on Android - you should be using `row` or `column`.

2023-03-22 07:12 UTC, sauhardjain requested changes
Good work so far Ethan! Left some comments mostly about code quality and styling practices. 

Apart from these, the `EditEmailScreen` and `EditPhoneScreen` look a bit inconsistent with the Figma designs. Can you make sure that the input fields are the same size as the buttons on these screens?

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +// import { DarkGrayText } from '../auth/styles';
Remove this

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +const v4vLogo = require('../../../assets/logo-1.png');
Remove these and replace with the StandardLogo (components/common)

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +        <LogoContainer source={v4vLogo} />
Use the StandardLogo component here

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +      <View>
This `View` seems redundant

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +          <H2Heading>Hi, Derby Food Market!</H2Heading>
Add a TODO comment here about fetching the actual vendor name using AuthContext.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +          <H4CardNavTab>email@email.com</H4CardNavTab>
Add a TODO comment here about fetching the actual vendor email from AuthContext.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +          <H4CardNavTab>(123) 456-7890</H4CardNavTab>
TODO comment here about fetching the actual vendor phone number from AuthContext.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/ProfileScreen.tsx
> +      </ButtonBottomContainer>
What does this do?

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/styles.ts
> +`;
Since these styles are exactly the same, we can just use one component for all three buttons.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/styles.ts
> +`;
Is this style unused?

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/styles.ts
> +  margin-top: -6.3%;
Not a good practice to put specific margins in Text styles. Also, all Text styles should live in `assets/Fonts.tsx`.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/styles.ts
> +  color: #000000;
Use one of the global colors here.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/styles.ts
> +`;
Remove after replacing with StandardLogo.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/styles.ts
> +  margin-bottom: 124px;
Add a `margin-top` to the container that houses the Update buttons instead.

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/EditPhoneScreen.tsx
> +      <View>
Is this `View` necessary?

2023-03-22 07:12 UTC, sauhardjain commented on src/screens/profile/EditEmailScreen.tsx
> +      <View>
Is this `View` necessary?

2023-03-23 08:55 UTC, EthanAuyeung commented
Fixed commit comments ready for review

2023-03-23 09:03 UTC, EthanAuyeung commented
Not sure how to fix the lint error.

2023-04-10 22:17 UTC, closed without merging