[scanning] Implement ReviewScreen and ConfirmationScreen (screens/scanning)
calblueprint/vouchers4veggies pull request #68
Opened 2023-03-24 11:00 UTC by selene-huang

[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
- Updated ScanningContext to include edit, delete, and reset functionalities (EDIT_VOUCHER, DELETE_VOUCHER, and NEW_INVOICE respectively)
- Implemented hifi interfaces for Review screen and Confirmation screen
- Moved some frontend components into common utilities
- Fixed issue in ConfirmValueScreen that led to values being saved in dollars rather than cents
- Added some basic input validation for serial numbers in ManualVoucherScreen, but see **next steps** for more details

**Notes on the Review Screen:**

We had initially intended there to be a set box for the vouchers to be viewed, leaving the submit button in the same position no matter what and displaying up to 4 or 5 vouchers at a time. The user was then supposed to scroll through the rest. However, we found there was no easy way to indicate that the user should scroll, so we opted instead to include the submit button as part of the scroll.

I have set a minimum height for the vouchers being displayed so that the submit button at least has some consistency in its positioning.

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy!"
Serial Number Validation: 
![image](https://user-images.githubusercontent.com/57937407/227498161-a68b821c-b52f-4b57-bcad-4d5b76f54cef.png)

Review Screen (short):
![image](https://user-images.githubusercontent.com/57937407/227498261-e4c3899b-f22f-4ddc-ad6e-f764bb0ddf94.png)

Review Screen (with scrolling):
![image](https://user-images.githubusercontent.com/57937407/227498318-e55022a3-0e5c-4b82-846f-19fa9a01d730.png)

Android Review Screen Alert Samples:
![image](https://user-images.githubusercontent.com/57937407/227498392-d973ab8d-1e60-4190-96ba-2c9613fb6cc4.png)
![image](https://user-images.githubusercontent.com/57937407/227498415-07a12808-a540-4244-a3c3-2545cf8719ea.png)

Confirmation Screen:
![image](https://user-images.githubusercontent.com/57937407/227498473-22b56042-716c-48b2-ac77-8b0c9614a6d5.png)

## How to review
[//]: # "Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?"

Run `npx expo start`. Navigate the scanning flow and press Add Manually. Input a serial number in the range from 100-110 (but note that some may be invalid because they are already in use). Check that input validation works as intended, and that you can edit and delete vouchers as you please before submitting. Check that the confirmation screen navigates to the correct screens afterwards.

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

Input validation is only partially implemented in this PR. There are simultaneously overlapping checks within queries and the scanning flow (and not all of these agree with each other), while some areas have no validation whatsoever.

Serial number validation has been fully implemented in this PR for the sake of adding vouchers.

Voucher amount validation is currently hard-coded in the scanning flow and properly implemented within queries. This means that it will work for now, but I imagine there will be cases in the future where this becomes a problem, so it should probably be fixed when we have more time.

## Relevant Links

### Online sources
[//]: # "Optional - copy links to any tutorials or documentation that was useful to you when working on this PR"

React native does not support inputs for alerts on Android. The [Dialog package](https://www.npmjs.com/package/react-native-dialog?activeTab=readme) is a useful work around.

### Related PRs
[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

Refactors code from #29 and #58 
Builds upon input validation from #49 

[//]: # "This tags the project leader as a default. Feel free to change, or add on anyone who you should be in on the conversation."
🥦 CC: @sauhardjain

2023-03-27 15:28 UTC, kbrgl requested changes
Great PR! Love the commit discipline. :)

A few minor changes here and there. Slack me if you have any questions.

2023-03-27 15:28 UTC, kbrgl commented on src/components/InputField/InputField.tsx
> +        // eslint-disable-next-line no-nested-ternary
I suggest rewriting as an if statement—not the most readable right now. Here's some code you can use if you want. Add it before the return:
```
let textInputStyle;

if (active) {
  textInputStyle = Styles.FormFieldFocus;
} else if (isValid) {
  textInputStyle = Styles.FormField;
} else {
  textInputStyle = Styles.FormFieldError;
}
```
and then pass `textInputStyle` in here.

2023-03-27 15:28 UTC, kbrgl commented on src/components/common/BackButton.tsx
Pretty sure that implementing a custom button here is not the move, regardless of what the Figma says. React Navigation should IIRC already allow you to add a header with a back button. Further, I believe React Navigation also allows you to customize this header: https://reactnavigation.org/docs/header-buttons/#overriding-the-back-button

cc @sauhardjain

2023-03-27 15:28 UTC, kbrgl commented on src/navigation/stacks/ScannerStackNavigator.tsx
> +          name="Transactions"
Rename to TransactionsScreen?

2023-03-27 15:28 UTC, kbrgl commented on src/screens/auth/ForgotPasswordScreen.tsx
> +        {BackButton(() => navigation.navigate('Login'))}
This is not how you use a React component—it should always be used with the JSX syntax (`<BackButton onPress={...} />`. Here, you're just calling the component as a function. Resources on why not to do this:

https://dev.to/igor_bykov/react-calling-functional-components-as-functions-1d3l
https://kentcdodds.com/blog/dont-call-a-react-function-component

2023-03-27 15:28 UTC, kbrgl commented on src/screens/auth/LoginScreen.tsx
> +        {BackButton(() => navigation.navigate('Start'))}
Don't call here

2023-03-27 15:28 UTC, kbrgl commented on src/screens/scanning/ConfirmationScreen.tsx
> +      <StandardHeader>{BackButton(() => navigation.goBack())}</StandardHeader>
Don't call here

2023-03-27 15:28 UTC, kbrgl commented on src/screens/scanning/ConfirmationScreen.tsx
> +      <StandardHeader>{BackButton(() => navigation.goBack())}</StandardHeader>
(To reiterate, use as a React component with JSX syntax)

2023-03-27 15:28 UTC, kbrgl commented on src/screens/transactions/TransactionDetailsScreen.tsx
> +        {BackButton(() => navigation.navigate('TransactionsScreen'))}
Don't call here

2023-03-30 20:16 UTC, sauhardjain reviewed
Leaving notes for bugs to be fixed:
1. Async validation calls on voucher entry form taking too long: results in an error message at first which goes away on a second try.
2. Screen shifts down when keyboard opens.

2023-04-01 18:59 UTC, sauhardjain approved these changes
lgtm THANKS @selene-huang

2023-04-01 19:00 UTC, merged